// This file was generated by Prisma.
// DATABASE_URL is provided directly via the environment (Railway / docker-compose),
// so no .env loading is needed here.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
